// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'backtest_provider.dart';

// **************************************************************************
// RiverpodGenerator
// **************************************************************************

// To be generated by running: flutter pub run build_runner build
