// Mocks generated by Mockito 5.4.4 from annotations
// in kuri_crypto/test/services/ai_analysis_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i2;
import 'package:kuri_crypto/services/matp_api_client.dart' as _i4;
import 'package:kuri_crypto/services/rate_limit_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MATPApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMATPApiClient extends _i1.Mock implements _i4.MATPApiClient {
  MockMATPApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get userLevel => (super.noSuchMethod(
        Invocation.getter(#userLevel),
        returnValue: 0,
      ) as int);

  @override
  bool get isTokenExpired => (super.noSuchMethod(
        Invocation.getter(#isTokenExpired),
        returnValue: false,
      ) as bool);

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  set dioInstance(_i2.Dio? testDio) => super.noSuchMethod(
        Invocation.setter(
          #dioInstance,
          testDio,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#environment),
        ),
      ) as String);

  @override
  void setJWTToken(
    String? token, {
    String? refreshToken,
    DateTime? expiry,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setJWTToken,
          [token],
          {
            #refreshToken: refreshToken,
            #expiry: expiry,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearJWTToken() => super.noSuchMethod(
        Invocation.method(
          #clearJWTToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserLevel(int? level) => super.noSuchMethod(
        Invocation.method(
          #setUserLevel,
          [level],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasAccessLevel(int? requiredLevel) => (super.noSuchMethod(
        Invocation.method(
          #hasAccessLevel,
          [requiredLevel],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> refreshJWTToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshJWTToken,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<T> matpGet<T>(
    String? path, {
    int? requiredLevel,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i6.RequestPriority? priority = _i6.RequestPriority.normal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matpGet,
          [path],
          {
            #requiredLevel: requiredLevel,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #priority: priority,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #matpGet,
                  [path],
                  {
                    #requiredLevel: requiredLevel,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #priority: priority,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #matpGet,
                [path],
                {
                  #requiredLevel: requiredLevel,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #priority: priority,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> matpPost<T>(
    String? path, {
    int? requiredLevel,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i6.RequestPriority? priority = _i6.RequestPriority.normal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matpPost,
          [path],
          {
            #requiredLevel: requiredLevel,
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #priority: priority,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #matpPost,
                  [path],
                  {
                    #requiredLevel: requiredLevel,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #priority: priority,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #matpPost,
                [path],
                {
                  #requiredLevel: requiredLevel,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #priority: priority,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> matpPut<T>(
    String? path, {
    int? requiredLevel,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i6.RequestPriority? priority = _i6.RequestPriority.normal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matpPut,
          [path],
          {
            #requiredLevel: requiredLevel,
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #priority: priority,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #matpPut,
                  [path],
                  {
                    #requiredLevel: requiredLevel,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #priority: priority,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #matpPut,
                [path],
                {
                  #requiredLevel: requiredLevel,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #priority: priority,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> matpDelete<T>(
    String? path, {
    int? requiredLevel,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i6.RequestPriority? priority = _i6.RequestPriority.normal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matpDelete,
          [path],
          {
            #requiredLevel: requiredLevel,
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #priority: priority,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #matpDelete,
                  [path],
                  {
                    #requiredLevel: requiredLevel,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #priority: priority,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #matpDelete,
                [path],
                {
                  #requiredLevel: requiredLevel,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #priority: priority,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  Map<String, dynamic> getRateLimitStatus() => (super.noSuchMethod(
        Invocation.method(
          #getRateLimitStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearState() => super.noSuchMethod(
        Invocation.method(
          #clearState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<T> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #get,
                [path],
                {
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onSendProgress,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #post,
                [path],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onSendProgress,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #put,
                [path],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #delete,
                [path],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onSendProgress,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.ifNotNull(
              _i5.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #patch,
                [path],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateBaseUrl(String? newBaseUrl) => super.noSuchMethod(
        Invocation.method(
          #updateBaseUrl,
          [newBaseUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
}
