// Mocks generated by Mockito 5.4.4 from annotations
// in kuri_crypto/test/services/enhanced_trading_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i2;
import 'package:kuri_crypto/models/mcp_account_info.dart' as _i10;
import 'package:kuri_crypto/models/mcp_balance.dart' as _i11;
import 'package:kuri_crypto/models/mcp_bollinger_bands.dart' as _i8;
import 'package:kuri_crypto/models/mcp_candle.dart' as _i17;
import 'package:kuri_crypto/models/mcp_macd_result.dart' as _i7;
import 'package:kuri_crypto/models/mcp_orderbook.dart' as _i5;
import 'package:kuri_crypto/models/mcp_portfolio.dart' as _i12;
import 'package:kuri_crypto/models/mcp_rsi_result.dart' as _i6;
import 'package:kuri_crypto/models/mcp_ticker.dart' as _i4;
import 'package:kuri_crypto/models/mcp_trading_signal.dart' as _i9;
import 'package:kuri_crypto/services/matp_api_client.dart' as _i13;
import 'package:kuri_crypto/services/mcp_tools_service.dart' as _i16;
import 'package:kuri_crypto/services/rate_limit_service.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_1<T1> extends _i1.SmartFake implements _i3.Future<T1> {
  _FakeFuture_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPTicker_2 extends _i1.SmartFake implements _i4.MCPTicker {
  _FakeMCPTicker_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPOrderBook_3 extends _i1.SmartFake implements _i5.MCPOrderBook {
  _FakeMCPOrderBook_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPRSIResult_4 extends _i1.SmartFake implements _i6.MCPRSIResult {
  _FakeMCPRSIResult_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPMACDResult_5 extends _i1.SmartFake implements _i7.MCPMACDResult {
  _FakeMCPMACDResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPBollingerBands_6 extends _i1.SmartFake
    implements _i8.MCPBollingerBands {
  _FakeMCPBollingerBands_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPTradingSignal_7 extends _i1.SmartFake
    implements _i9.MCPTradingSignal {
  _FakeMCPTradingSignal_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPAccountInfo_8 extends _i1.SmartFake
    implements _i10.MCPAccountInfo {
  _FakeMCPAccountInfo_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPBalance_9 extends _i1.SmartFake implements _i11.MCPBalance {
  _FakeMCPBalance_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMCPPortfolio_10 extends _i1.SmartFake implements _i12.MCPPortfolio {
  _FakeMCPPortfolio_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MATPApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockMATPApiClient extends _i1.Mock implements _i13.MATPApiClient {
  MockMATPApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get userLevel => (super.noSuchMethod(
        Invocation.getter(#userLevel),
        returnValue: 0,
      ) as int);

  @override
  bool get isTokenExpired => (super.noSuchMethod(
        Invocation.getter(#isTokenExpired),
        returnValue: false,
      ) as bool);

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);

  @override
  set dioInstance(_i2.Dio? testDio) => super.noSuchMethod(
        Invocation.setter(
          #dioInstance,
          testDio,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get environment => (super.noSuchMethod(
        Invocation.getter(#environment),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#environment),
        ),
      ) as String);

  @override
  void setJWTToken(
    String? token, {
    String? refreshToken,
    DateTime? expiry,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setJWTToken,
          [token],
          {
            #refreshToken: refreshToken,
            #expiry: expiry,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearJWTToken() => super.noSuchMethod(
        Invocation.method(
          #clearJWTToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserLevel(int? level) => super.noSuchMethod(
        Invocation.method(
          #setUserLevel,
          [level],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool hasAccessLevel(int? requiredLevel) => (super.noSuchMethod(
        Invocation.method(
          #hasAccessLevel,
          [requiredLevel],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> refreshJWTToken() => (super.noSuchMethod(
        Invocation.method(
          #refreshJWTToken,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<T> matpGet<T>(
    String? path, {
    int? requiredLevel,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i15.RequestPriority? priority = _i15.RequestPriority.normal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matpGet,
          [path],
          {
            #requiredLevel: requiredLevel,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #priority: priority,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #matpGet,
                  [path],
                  {
                    #requiredLevel: requiredLevel,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #priority: priority,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #matpGet,
                [path],
                {
                  #requiredLevel: requiredLevel,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #priority: priority,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> matpPost<T>(
    String? path, {
    int? requiredLevel,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i15.RequestPriority? priority = _i15.RequestPriority.normal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matpPost,
          [path],
          {
            #requiredLevel: requiredLevel,
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #priority: priority,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #matpPost,
                  [path],
                  {
                    #requiredLevel: requiredLevel,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #priority: priority,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #matpPost,
                [path],
                {
                  #requiredLevel: requiredLevel,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #priority: priority,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> matpPut<T>(
    String? path, {
    int? requiredLevel,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i15.RequestPriority? priority = _i15.RequestPriority.normal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matpPut,
          [path],
          {
            #requiredLevel: requiredLevel,
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #priority: priority,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #matpPut,
                  [path],
                  {
                    #requiredLevel: requiredLevel,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #priority: priority,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #matpPut,
                [path],
                {
                  #requiredLevel: requiredLevel,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #priority: priority,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> matpDelete<T>(
    String? path, {
    int? requiredLevel,
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i15.RequestPriority? priority = _i15.RequestPriority.normal,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #matpDelete,
          [path],
          {
            #requiredLevel: requiredLevel,
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #priority: priority,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #matpDelete,
                  [path],
                  {
                    #requiredLevel: requiredLevel,
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #priority: priority,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #matpDelete,
                [path],
                {
                  #requiredLevel: requiredLevel,
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #priority: priority,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  Map<String, dynamic> getRateLimitStatus() => (super.noSuchMethod(
        Invocation.method(
          #getRateLimitStatus,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void clearState() => super.noSuchMethod(
        Invocation.method(
          #clearState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<T> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #get,
                [path],
                {
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onSendProgress,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #post,
                [path],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onSendProgress,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #put,
                [path],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #delete,
                [path],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  _i3.Future<T> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    void Function(
      int,
      int,
    )? onSendProgress,
    void Function(
      int,
      int,
    )? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i14.ifNotNull(
              _i14.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
              (T v) => _i3.Future<T>.value(v),
            ) ??
            _FakeFuture_1<T>(
              this,
              Invocation.method(
                #patch,
                [path],
                {
                  #data: data,
                  #queryParameters: queryParameters,
                  #options: options,
                  #cancelToken: cancelToken,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            ),
      ) as _i3.Future<T>);

  @override
  void setAuthToken(String? token) => super.noSuchMethod(
        Invocation.method(
          #setAuthToken,
          [token],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearAuthToken() => super.noSuchMethod(
        Invocation.method(
          #clearAuthToken,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateBaseUrl(String? newBaseUrl) => super.noSuchMethod(
        Invocation.method(
          #updateBaseUrl,
          [newBaseUrl],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MCPToolsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMCPToolsService extends _i1.Mock implements _i16.MCPToolsService {
  MockMCPToolsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.MCPTicker> getTicker(
    String? exchange,
    String? pair, {
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTicker,
          [
            exchange,
            pair,
          ],
          {#marketType: marketType},
        ),
        returnValue: _i3.Future<_i4.MCPTicker>.value(_FakeMCPTicker_2(
          this,
          Invocation.method(
            #getTicker,
            [
              exchange,
              pair,
            ],
            {#marketType: marketType},
          ),
        )),
      ) as _i3.Future<_i4.MCPTicker>);

  @override
  _i3.Future<List<_i17.MCPCandle>> getCandles(
    String? exchange,
    String? pair,
    String? interval,
    int? limit, {
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCandles,
          [
            exchange,
            pair,
            interval,
            limit,
          ],
          {#marketType: marketType},
        ),
        returnValue: _i3.Future<List<_i17.MCPCandle>>.value(<_i17.MCPCandle>[]),
      ) as _i3.Future<List<_i17.MCPCandle>>);

  @override
  _i3.Future<_i5.MCPOrderBook> getOrderBook(
    String? exchange,
    String? pair, {
    int? depth = 20,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrderBook,
          [
            exchange,
            pair,
          ],
          {
            #depth: depth,
            #marketType: marketType,
          },
        ),
        returnValue: _i3.Future<_i5.MCPOrderBook>.value(_FakeMCPOrderBook_3(
          this,
          Invocation.method(
            #getOrderBook,
            [
              exchange,
              pair,
            ],
            {
              #depth: depth,
              #marketType: marketType,
            },
          ),
        )),
      ) as _i3.Future<_i5.MCPOrderBook>);

  @override
  _i3.Future<List<String>> getMarkets(
    String? exchange, {
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkets,
          [exchange],
          {#marketType: marketType},
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<double> getMarkPrice(
    String? exchange,
    String? pair,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMarkPrice,
          [
            exchange,
            pair,
          ],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<_i6.MCPRSIResult> calculateRSI(
    String? exchange,
    String? pair, {
    int? period = 14,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRSI,
          [
            exchange,
            pair,
          ],
          {
            #period: period,
            #marketType: marketType,
          },
        ),
        returnValue: _i3.Future<_i6.MCPRSIResult>.value(_FakeMCPRSIResult_4(
          this,
          Invocation.method(
            #calculateRSI,
            [
              exchange,
              pair,
            ],
            {
              #period: period,
              #marketType: marketType,
            },
          ),
        )),
      ) as _i3.Future<_i6.MCPRSIResult>);

  @override
  _i3.Future<_i7.MCPMACDResult> calculateMACD(
    String? exchange,
    String? pair, {
    int? fastPeriod = 12,
    int? slowPeriod = 26,
    int? signalPeriod = 9,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMACD,
          [
            exchange,
            pair,
          ],
          {
            #fastPeriod: fastPeriod,
            #slowPeriod: slowPeriod,
            #signalPeriod: signalPeriod,
            #marketType: marketType,
          },
        ),
        returnValue: _i3.Future<_i7.MCPMACDResult>.value(_FakeMCPMACDResult_5(
          this,
          Invocation.method(
            #calculateMACD,
            [
              exchange,
              pair,
            ],
            {
              #fastPeriod: fastPeriod,
              #slowPeriod: slowPeriod,
              #signalPeriod: signalPeriod,
              #marketType: marketType,
            },
          ),
        )),
      ) as _i3.Future<_i7.MCPMACDResult>);

  @override
  _i3.Future<_i8.MCPBollingerBands> calculateBollingerBands(
    String? exchange,
    String? pair, {
    int? period = 20,
    double? stdDev = 2.0,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateBollingerBands,
          [
            exchange,
            pair,
          ],
          {
            #period: period,
            #stdDev: stdDev,
            #marketType: marketType,
          },
        ),
        returnValue:
            _i3.Future<_i8.MCPBollingerBands>.value(_FakeMCPBollingerBands_6(
          this,
          Invocation.method(
            #calculateBollingerBands,
            [
              exchange,
              pair,
            ],
            {
              #period: period,
              #stdDev: stdDev,
              #marketType: marketType,
            },
          ),
        )),
      ) as _i3.Future<_i8.MCPBollingerBands>);

  @override
  _i3.Future<double> calculateEMA(
    String? exchange,
    String? pair,
    int? period, {
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateEMA,
          [
            exchange,
            pair,
            period,
          ],
          {#marketType: marketType},
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<double> calculateSMA(
    String? exchange,
    String? pair,
    int? period, {
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateSMA,
          [
            exchange,
            pair,
            period,
          ],
          {#marketType: marketType},
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<double> calculateATR(
    String? exchange,
    String? pair, {
    int? period = 14,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateATR,
          [
            exchange,
            pair,
          ],
          {
            #period: period,
            #marketType: marketType,
          },
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<Map<String, double>> calculateStochastic(
    String? exchange,
    String? pair, {
    int? kPeriod = 14,
    int? dPeriod = 3,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateStochastic,
          [
            exchange,
            pair,
          ],
          {
            #kPeriod: kPeriod,
            #dPeriod: dPeriod,
            #marketType: marketType,
          },
        ),
        returnValue: _i3.Future<Map<String, double>>.value(<String, double>{}),
      ) as _i3.Future<Map<String, double>>);

  @override
  _i3.Future<double> calculateADX(
    String? exchange,
    String? pair, {
    int? period = 14,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateADX,
          [
            exchange,
            pair,
          ],
          {
            #period: period,
            #marketType: marketType,
          },
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<double> calculateCCI(
    String? exchange,
    String? pair, {
    int? period = 20,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateCCI,
          [
            exchange,
            pair,
          ],
          {
            #period: period,
            #marketType: marketType,
          },
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<double> calculateWilliamsR(
    String? exchange,
    String? pair, {
    int? period = 14,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateWilliamsR,
          [
            exchange,
            pair,
          ],
          {
            #period: period,
            #marketType: marketType,
          },
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<Map<int, double>> calculateMultipleEMAs(
    String? exchange,
    String? pair,
    List<int>? periods, {
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMultipleEMAs,
          [
            exchange,
            pair,
            periods,
          ],
          {#marketType: marketType},
        ),
        returnValue: _i3.Future<Map<int, double>>.value(<int, double>{}),
      ) as _i3.Future<Map<int, double>>);

  @override
  _i3.Future<_i9.MCPTradingSignal> getCompleteAnalysis(
    String? exchange,
    String? pair, {
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompleteAnalysis,
          [
            exchange,
            pair,
          ],
          {#marketType: marketType},
        ),
        returnValue:
            _i3.Future<_i9.MCPTradingSignal>.value(_FakeMCPTradingSignal_7(
          this,
          Invocation.method(
            #getCompleteAnalysis,
            [
              exchange,
              pair,
            ],
            {#marketType: marketType},
          ),
        )),
      ) as _i3.Future<_i9.MCPTradingSignal>);

  @override
  _i3.Future<Map<String, dynamic>> runBacktest(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #runBacktest,
          [request],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> optimizeParameters(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #optimizeParameters,
          [request],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> compareStrategies(
          List<Map<String, dynamic>>? strategies) =>
      (super.noSuchMethod(
        Invocation.method(
          #compareStrategies,
          [strategies],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<_i10.MCPAccountInfo> getAccountInfo(String? exchange) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountInfo,
          [exchange],
        ),
        returnValue:
            _i3.Future<_i10.MCPAccountInfo>.value(_FakeMCPAccountInfo_8(
          this,
          Invocation.method(
            #getAccountInfo,
            [exchange],
          ),
        )),
      ) as _i3.Future<_i10.MCPAccountInfo>);

  @override
  _i3.Future<_i11.MCPBalance> getBalance(
    String? exchange,
    String? currency,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBalance,
          [
            exchange,
            currency,
          ],
        ),
        returnValue: _i3.Future<_i11.MCPBalance>.value(_FakeMCPBalance_9(
          this,
          Invocation.method(
            #getBalance,
            [
              exchange,
              currency,
            ],
          ),
        )),
      ) as _i3.Future<_i11.MCPBalance>);

  @override
  _i3.Future<_i12.MCPPortfolio> getPortfolio() => (super.noSuchMethod(
        Invocation.method(
          #getPortfolio,
          [],
        ),
        returnValue: _i3.Future<_i12.MCPPortfolio>.value(_FakeMCPPortfolio_10(
          this,
          Invocation.method(
            #getPortfolio,
            [],
          ),
        )),
      ) as _i3.Future<_i12.MCPPortfolio>);

  @override
  _i3.Future<Map<String, dynamic>> getPortfolioAnalysis() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPortfolioAnalysis,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> calculatePositionSize(
          Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculatePositionSize,
          [request],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getRiskState() => (super.noSuchMethod(
        Invocation.method(
          #getRiskState,
          [],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getExposure({String? exchange}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExposure,
          [],
          {#exchange: exchange},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> assessRisk(Map<String, dynamic>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #assessRisk,
          [request],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<String>> getAvailableTools() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableTools,
          [],
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<Map<String, dynamic>> callTool(
    String? toolName,
    Map<String, dynamic>? arguments, {
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callTool,
          [
            toolName,
            arguments,
          ],
          {#marketType: marketType},
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> callMultipleTools(
          List<Map<String, dynamic>>? calls) =>
      (super.noSuchMethod(
        Invocation.method(
          #callMultipleTools,
          [calls],
        ),
        returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i3.Future<List<Map<String, dynamic>>>);
}
