// Mocks generated by Mockito 5.4.4 from annotations
// in kuri_crypto/test/services/mcp_tools_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:kuri_crypto/services/mcp_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MCPService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMCPService extends _i1.Mock implements _i3.MCPService {
  MockMCPService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get nextRequestId => (super.noSuchMethod(
        Invocation.getter(#nextRequestId),
        returnValue: 0,
      ) as int);

  @override
  _i2.Future<Map<String, dynamic>> callTool({
    required String? toolName,
    required Map<String, dynamic>? arguments,
    String? marketType,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callTool,
          [],
          {
            #toolName: toolName,
            #arguments: arguments,
            #marketType: marketType,
          },
        ),
        returnValue:
            _i2.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<T> callToolTyped<T>({
    required String? toolName,
    required Map<String, dynamic>? arguments,
    String? marketType,
    required T Function(Map<String, dynamic>)? fromJson,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #callToolTyped,
          [],
          {
            #toolName: toolName,
            #arguments: arguments,
            #marketType: marketType,
            #fromJson: fromJson,
          },
        ),
        returnValue: _i4.ifNotNull(
              _i4.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #callToolTyped,
                  [],
                  {
                    #toolName: toolName,
                    #arguments: arguments,
                    #marketType: marketType,
                    #fromJson: fromJson,
                  },
                ),
              ),
              (T v) => _i2.Future<T>.value(v),
            ) ??
            _FakeFuture_0<T>(
              this,
              Invocation.method(
                #callToolTyped,
                [],
                {
                  #toolName: toolName,
                  #arguments: arguments,
                  #marketType: marketType,
                  #fromJson: fromJson,
                },
              ),
            ),
      ) as _i2.Future<T>);

  @override
  _i2.Future<List<Map<String, dynamic>>> callMultipleTools(
          List<Map<String, dynamic>>? calls) =>
      (super.noSuchMethod(
        Invocation.method(
          #callMultipleTools,
          [calls],
        ),
        returnValue: _i2.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i2.Future<List<Map<String, dynamic>>>);

  @override
  _i2.Future<List<String>> getAvailableTools() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableTools,
          [],
        ),
        returnValue: _i2.Future<List<String>>.value(<String>[]),
      ) as _i2.Future<List<String>>);

  @override
  void resetRequestId() => super.noSuchMethod(
        Invocation.method(
          #resetRequestId,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
