// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBSy2ecD_ekIhhr4Xrt2pmKP9g0tZDXZ8',
    appId: '1:1059556951172:web:710cc0f58427eb6271eed1',
    messagingSenderId: '1059556951172',
    projectId: 'kuri-crypto',
    authDomain: 'kuri-crypto.firebaseapp.com',
    storageBucket: 'kuri-crypto.firebasestorage.app',
    measurementId: 'G-TD5PBJW7TH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ceJDM4404KkOlYtNL3Ldrm019eh-AFM',
    appId: '1:1059556951172:android:2b1b9607c52ff92a71eed1',
    messagingSenderId: '1059556951172',
    projectId: 'kuri-crypto',
    storageBucket: 'kuri-crypto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEuBz5nRCaofqRiPAlZjw91AJSyaXBBWA',
    appId: '1:1059556951172:ios:305099cf27bb8a1f71eed1',
    messagingSenderId: '1059556951172',
    projectId: 'kuri-crypto',
    storageBucket: 'kuri-crypto.firebasestorage.app',
    iosBundleId: 'com.example.kuriCrypto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEuBz5nRCaofqRiPAlZjw91AJSyaXBBWA',
    appId: '1:1059556951172:ios:305099cf27bb8a1f71eed1',
    messagingSenderId: '1059556951172',
    projectId: 'kuri-crypto',
    storageBucket: 'kuri-crypto.firebasestorage.app',
    iosBundleId: 'com.example.kuriCrypto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBSy2ecD_ekIhhr4Xrt2pmKP9g0tZDXZ8',
    appId: '1:1059556951172:web:27e9318067a31f3271eed1',
    messagingSenderId: '1059556951172',
    projectId: 'kuri-crypto',
    authDomain: 'kuri-crypto.firebaseapp.com',
    storageBucket: 'kuri-crypto.firebasestorage.app',
    measurementId: 'G-YZLEXPC4EY',
  );
}
